version: "3.9"
services:
  backend:
    container_name: exceed-backend
    build: ./backend
    ports:
      - 3000:3000
  frontend:
    container_name: exceed-frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8080:8080
    